
Architecture: "dumby-mlp"

Seed: 42

Setting: "en22"

Logger:
    save_dir: "experiments/"

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 5

Trainer:
    gpus: [4, 5]
    strategy: 'ddp'
    accumulate_grad_batches: 8
    precision: 16
    log_every_n_steps: 32
    max_epochs: 100
    gradient_clip_val: 1
    val_check_interval: 0.1
  
Data:
    base_dir: "/workspace/data/scratch/L2_minicubes/" 
    test_track: "iid"
    train_batch_size: 4 #96
    val_batch_size: 1
    test_batch_size: 1 #96
    num_workers: 8 #2

Task:
    loss:
        name: "masked"
        args: {
            distance_type: "L2",
            rescale: True
        }
        dist_scale: 1
        ndvi: True
        min_lc: 2
        max_lc: 6
        comp_ndvi: True
    context_length: 35
    target_length: 10
    n_stochastic_preds: 1
    optimization:
        optimizer:
            - 
                name: Adam
                args: 
                    betas: [0.9, 0.999]
                lr_per_sample: 0.000001
    n_log_batches: 8
    compute_metric_on_test: True

Model:
    bias: True
    input: 'NDVI+T+W'