Architecture: "simvp"

Seed: 42

Setting: "en21x"

Logger:
    save_dir: "experiments/"

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
    gpus: 1 #6
    strategy: 'ddp'
    #deterministic: True
    log_every_n_steps: 32
    #profiler: 'advanced'
    #fast_dev_run: True
    #log_gpu_memory: 'all'
    #weights_summary: 'full'
    max_epochs: 100
    #limit_train_batches: 32
    #limit_val_batches: 32
    gradient_clip_val: 1
    #val_check_interval: 0.25
  
Data:
    base_dir: "/scratch/vbenson/earthnet2021x/" #"/Net/Groups/BGI/work_1/scratch/s3/earthnet/earthnet2021x/"
    test_track: "iid"
    train_batch_size: 64 #96
    val_batch_size: 8
    test_batch_size: 8 #96
    num_workers: 32 #2
    dl_cloudmask: True
    allow_fastaccess: True
    new_valset: True

Task:
    loss:
        name: "MaskedL2NDVILoss"
        min_lc: 10
        max_lc: 40
        ndvi_pred_idx: 0
        ndvi_targ_idx: 0
        pred_mask_value: -1
        scale_by_std: False
    context_length: 10
    target_length: 20
    n_stochastic_preds: 1
    optimization:
        optimizer:
            - 
                name: AdamW
                args: 
                    betas: [0.9, 0.999]
                lr_per_sample: 0.00001
        lr_shedule:
            -
                name: MultiStepLR
                args:
                    milestones: [190] #[2, 20, 50, 90]
                    gamma: 0.1
    n_log_batches: 2
    compute_metric_on_test: True

Model:
    enc_in_channels: 8
    encdec_hid_channels: 64
    encdec_depth: 4
    weather_in_channels: 24
    proc_hid_channels: 128
    proc_depth: 4
    dec_out_channels: 1
    gsta_processor: True
    weather_conditioning: "cat"
    weather_conditioning_loc: "latent"
    encdec_type: "PatchMerge"
    encdec_norm: "group"
    encdec_act: "leakyrelu"
    encdec_filtersize: 5
    encdec_readoutact: tanh
    mlp_after_attn: False
